
underlay:
    local:
        asn: 65001
    neighbors:
      - interface: et-0/0/12
        name: spine-04
        asn: 65014
        peer_ip: 172.16.0.20
        local_ip: 172.16.0.21
      - interface: et-0/0/14
        name: spine-02
        asn: 65012
        peer_ip: 172.16.0.12
        local_ip: 172.16.0.13
      - interface: et-0/0/13
        name: spine-03
        asn: 65013
        peer_ip: 172.16.0.16
        local_ip: 172.16.0.17
      - interface: et-0/0/15
        name: spine-01
        asn: 65011
        peer_ip: 172.16.0.8
        local_ip: 172.16.0.9
