

overlay:
    local:
        asn: 62000
    neighbors: [ 1.1.1.2, 1.1.10.1, 1.1.10.2, 1.1.10.3, 1.1.10.4 ]
    bridge_domains:
    - vlan_id: 100
      vni_id: 1000
      vip: 10.1.100.1
      ip: 10.1.100.2
      mask: 24
    - vlan_id: 101
      vni_id: 1001
      vip: 10.1.101.1
      ip: 10.1.101.2
      mask: 24
    - vlan_id: 102
      vni_id: 1002
      vip: 10.1.102.1
      ip: 10.1.102.2
      mask: 24
    - vlan_id: 103
      vni_id: 1003
      vip: 10.1.103.1
      ip: 10.1.103.2
      mask: 24
    - vlan_id: 104
      vni_id: 1004
      vip: 10.1.104.1
      ip: 10.1.104.2
      mask: 24
    - vlan_id: 105
      vni_id: 1005
      vip: 10.1.105.1
      ip: 10.1.105.2
      mask: 24
    - vlan_id: 106
      vni_id: 1006
      vip: 10.1.106.1
      ip: 10.1.106.2
      mask: 24
    - vlan_id: 107
      vni_id: 1007
      vip: 10.1.107.1
      ip: 10.1.107.2
      mask: 24
    - vlan_id: 108
      vni_id: 1008
      vip: 10.1.108.1
      ip: 10.1.108.2
      mask: 24
