
underlay:
    local:
        asn: 65002
    neighbors:
      - interface: et-0/0/12
        name: spine-04
        asn: 65014
        peer_ip: 172.16.0.22
        local_ip: 172.16.0.23
      - interface: et-0/0/14
        name: spine-02
        asn: 65012
        peer_ip: 172.16.0.14
        local_ip: 172.16.0.15
      - interface: et-0/0/13
        name: spine-03
        asn: 65013
        peer_ip: 172.16.0.18
        local_ip: 172.16.0.19
      - interface: et-0/0/15
        name: spine-01
        asn: 65011
        peer_ip: 172.16.0.10
        local_ip: 172.16.0.11
