
underlay:
    local:
        asn: 65011
    neighbors:
      - interface: et-0/0/59
        name: fabric-02
        asn: 65002
        peer_ip: 172.16.0.11
        local_ip: 172.16.0.10
      - interface: et-0/0/67
        name: leaf-02
        asn: 65022
        peer_ip: 172.16.0.1
        local_ip: 172.16.0.0
      - interface: et-0/0/58
        name: fabric-01
        asn: 65001
        peer_ip: 172.16.0.9
        local_ip: 172.16.0.8
      - interface: et-0/0/66
        name: leaf-01
        asn: 65021
        peer_ip: 172.16.0.1
        local_ip: 172.16.0.0
