underlay:
    local:
        asn: 60013
    neighbors:
## Fabric
      - interface: "{{ topo[inventory_hostname].port3.name }}"
        name: "{{ topo[inventory_hostname].port3.peer }}"
        asn: 60001
        peer_ip: "{{ p2p.link5.2}}"
        local_ip: "{{ p2p.link5.1}}"
      - interface: "{{ topo[inventory_hostname].port4.name }}"
        name: "{{ topo[inventory_hostname].port4.peer }}"
        asn: 60002
        peer_ip: "{{ p2p.link6.2}}"
        local_ip: "{{ p2p.link6.1}}"

## Leaf
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60023
        peer_ip: "{{ p2p.link13.2}}"
        local_ip: "{{ p2p.link13.1}}"
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60024
        peer_ip: "{{ p2p.link14.2}}"
        local_ip: "{{ p2p.link14.1}}"
