
access:
    interfaces:
        et-0/0/5:
            mode: trunk
            vlans: [ 100, 101, 102, 103, 104 ]
        ae0:
            mode: trunk
            esi: 00:01:01:01:01:01:01:01:01:02
            vlans: [ 100, 101, 102, 103, 104 ]
            lacp_system_id: 00:00:00:01:01:02
            lacp_mode: active
        et-0/0/49:
            mode: aggregate
            parent: ae0
