
underlay:
    local:
        asn: 65014
    neighbors:
      - interface: et-0/0/60
        name: fabric-02
        asn: 65002
        peer_ip: 172.16.0.23
        local_ip: 172.16.0.22
      - interface: et-0/0/67
        name: leaf-04
        asn: 65024
        peer_ip: 172.16.0.31
        local_ip: 172.16.0.30
      - interface: et-0/0/61
        name: fabric-01
        asn: 65001
        peer_ip: 172.16.0.21
        local_ip: 172.16.0.20
      - interface: et-0/0/66
        name: leaf-03
        asn: 65023
        peer_ip: 172.16.0.29
        local_ip: 172.16.0.28
